### ISSUE TITLE
Mockup

### ISSUE THREAD

**Issue by Jtfinlay** [IPPETAD/geerweek#1]
I'll try and get some mock ups done before the hackathon. That way we'll be able to flesh out all the features and how to organize them.

**Comment by Jtfinlay** [comment]
I got bored of drawing this. @afontaine , what do you think of UI ideas? Are we missing anything?

**Comment by afontaine** [comment]
Yeah, it looks good. Looks like we'll need some sort of web-side app as well with an admin panel to add/remove/edit shit as well (or make special APKs for the judges or something)

:shipit:
